all: rna_validacao

rna_validacao: rna_validacao.gp
	@echo Imagens RNA - Validacao...
	gnuplot rna_validacao.gp
	#mv *.eps ../imgs/rna/validacao
	@echo 

clean:
	@echo Removendo arquivos...
	#-rm ../imgs/rna/validacao/*.eps
